// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomepageDocumentDataSlicesSlice =
  | PurchaseButtonSlice
  | MarqueSlice
  | SwitchPlaygrounddSlice
  | ColorChangerSlice
  | BentoBoxSlice
  | HeroSlice;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Content for Product documents
 */
interface ProductDocumentData {
  /**
   * Name field in *Product*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Price (cents) field in *Product*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: product.price
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  price: prismic.NumberField;

  /**
   * Image field in *Product*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Product*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Product document from Prismic
 *
 * - **API ID**: `product`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductDocumentData>,
    "product",
    Lang
  >;

/**
 * Content for Switch documents
 */
interface SwitchDocumentData {
  /**
   * Name field in *Switch*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switch.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Hex Color field in *Switch*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: switch.hexcolor
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  hexcolor: prismic.ColorField;
}

/**
 * Switch document from Prismic
 *
 * - **API ID**: `switch`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SwitchDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<SwitchDocumentData>, "switch", Lang>;

export type AllDocumentTypes =
  | HomepageDocument
  | ProductDocument
  | SwitchDocument;

/**
 * Item in *BentoBox → Default → Primary → items*
 */
export interface BentoBoxSliceDefaultPrimaryItemsItem {
  /**
   * Size field in *BentoBox → Default → Primary → items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].size
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  size: prismic.SelectField<"Small" | "Medium" | "Large">;

  /**
   * Image field in *BentoBox → Default → Primary → items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Text field in *BentoBox → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Primary content in *BentoBox → Default → Primary*
 */
export interface BentoBoxSliceDefaultPrimary {
  /**
   * Heading field in *BentoBox → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * items field in *BentoBox → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: bento_box.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<Simplify<BentoBoxSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for BentoBox Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BentoBoxSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BentoBox*
 */
type BentoBoxSliceVariation = BentoBoxSliceDefault;

/**
 * BentoBox Shared Slice
 *
 * - **API ID**: `bento_box`
 * - **Description**: BentoBox
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BentoBoxSlice = prismic.SharedSlice<
  "bento_box",
  BentoBoxSliceVariation
>;

/**
 * Primary content in *ColorChanger → Default → Primary*
 */
export interface ColorChangerSliceDefaultPrimary {
  /**
   * Heading field in *ColorChanger → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: color_changer.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *ColorChanger → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: color_changer.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for ColorChanger Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColorChangerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ColorChangerSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ColorChanger*
 */
type ColorChangerSliceVariation = ColorChangerSliceDefault;

/**
 * ColorChanger Shared Slice
 *
 * - **API ID**: `color_changer`
 * - **Description**: ColorChanger
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ColorChangerSlice = prismic.SharedSlice<
  "color_changer",
  ColorChangerSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Body field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;

  /**
   * Buy Button Text field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.buy_button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  buy_button_text: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Marque → Default → Primary → Phrases*
 */
export interface MarqueSliceDefaultPrimaryPhrasesItem {
  /**
   * Text field in *Marque → Default → Primary → Phrases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: marque.default.primary.phrases[].text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  text: prismic.KeyTextField;
}

/**
 * Primary content in *Marque → Default → Primary*
 */
export interface MarqueSliceDefaultPrimary {
  /**
   * Directions field in *Marque → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: marque.default.primary.directions
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  directions: prismic.SelectField<"Left" | "Right">;

  /**
   * Phrases field in *Marque → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: marque.default.primary.phrases[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  phrases: prismic.GroupField<Simplify<MarqueSliceDefaultPrimaryPhrasesItem>>;
}

/**
 * Default variation for Marque Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MarqueSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Marque*
 */
type MarqueSliceVariation = MarqueSliceDefault;

/**
 * Marque Shared Slice
 *
 * - **API ID**: `marque`
 * - **Description**: Marque
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MarqueSlice = prismic.SharedSlice<"marque", MarqueSliceVariation>;

/**
 * Primary content in *PurchaseButton → Default → Primary*
 */
export interface PurchaseButtonSliceDefaultPrimary {
  /**
   * Eyebrow field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.eyebrow
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrow: prismic.KeyTextField;

  /**
   * Heading field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Button Text field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.button_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;

  /**
   * Body field in *PurchaseButton → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: purchase_button.default.primary.body
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for PurchaseButton Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PurchaseButtonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PurchaseButtonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PurchaseButton*
 */
type PurchaseButtonSliceVariation = PurchaseButtonSliceDefault;

/**
 * PurchaseButton Shared Slice
 *
 * - **API ID**: `purchase_button`
 * - **Description**: PurchaseButton
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PurchaseButtonSlice = prismic.SharedSlice<
  "purchase_button",
  PurchaseButtonSliceVariation
>;

/**
 * Item in *SwitchPlaygroundd → Default → Primary → Switches*
 */
export interface SwitchPlaygrounddSliceDefaultPrimarySwitchesItem {
  /**
   * Switch field in *SwitchPlaygroundd → Default → Primary → Switches*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playgroundd.default.primary.switches[].switch
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  switch: ContentRelationshipFieldWithData<
    [{ id: "switch"; fields: ["name", "hexcolor"] }]
  >;
}

/**
 * Primary content in *SwitchPlaygroundd → Default → Primary*
 */
export interface SwitchPlaygrounddSliceDefaultPrimary {
  /**
   * Heading field in *SwitchPlaygroundd → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playgroundd.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *SwitchPlaygroundd → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playgroundd.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Switches field in *SwitchPlaygroundd → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: switch_playgroundd.default.primary.switches[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  switches: prismic.GroupField<
    Simplify<SwitchPlaygrounddSliceDefaultPrimarySwitchesItem>
  >;
}

/**
 * Default variation for SwitchPlaygroundd Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SwitchPlaygrounddSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SwitchPlaygrounddSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SwitchPlaygroundd*
 */
type SwitchPlaygrounddSliceVariation = SwitchPlaygrounddSliceDefault;

/**
 * SwitchPlaygroundd Shared Slice
 *
 * - **API ID**: `switch_playgroundd`
 * - **Description**: SwitchPlaygroundd
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SwitchPlaygrounddSlice = prismic.SharedSlice<
  "switch_playgroundd",
  SwitchPlaygrounddSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ProductDocument,
      ProductDocumentData,
      SwitchDocument,
      SwitchDocumentData,
      AllDocumentTypes,
      BentoBoxSlice,
      BentoBoxSliceDefaultPrimaryItemsItem,
      BentoBoxSliceDefaultPrimary,
      BentoBoxSliceVariation,
      BentoBoxSliceDefault,
      ColorChangerSlice,
      ColorChangerSliceDefaultPrimary,
      ColorChangerSliceVariation,
      ColorChangerSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      MarqueSlice,
      MarqueSliceDefaultPrimaryPhrasesItem,
      MarqueSliceDefaultPrimary,
      MarqueSliceVariation,
      MarqueSliceDefault,
      PurchaseButtonSlice,
      PurchaseButtonSliceDefaultPrimary,
      PurchaseButtonSliceVariation,
      PurchaseButtonSliceDefault,
      SwitchPlaygrounddSlice,
      SwitchPlaygrounddSliceDefaultPrimarySwitchesItem,
      SwitchPlaygrounddSliceDefaultPrimary,
      SwitchPlaygrounddSliceVariation,
      SwitchPlaygrounddSliceDefault,
    };
  }
}
